#!/usr/bin/env python3
"""CLI entry-point for SteelVoiceMix actions outside the GUI.

Subcommands:
  sink cycle    — advance the default sink between loaded Steel sinks
  init          — drop a small user-side PipeWire config that helps the
                  filter chain run smoothly (locks default rate to 48kHz)
  clean         — remove what init wrote
  diagnose      — read-only system check; prints what looks healthy
                  and what doesn't

Bind `sink cycle` in your DE's keyboard settings for global hotkey:
    KDE   → System Settings → Shortcuts → Custom Shortcuts
    GNOME → Settings → Keyboard → Custom Shortcuts

Exit codes:
  0 — success
  1 — runtime/system error
  2 — usage error
"""

from __future__ import annotations

import json
import os
import sys
from pathlib import Path


def _load_settings() -> dict:
    """Read settings.json without importing PySide6 — keeps the
    CLI dependency-light so it runs without a display, in scripts,
    on headless servers etc."""
    base = os.environ.get("XDG_CONFIG_HOME") or os.path.expanduser("~/.config")
    path = Path(base) / "steelvoicemix" / "settings.json"
    try:
        with open(path) as f:
            data = json.load(f)
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _cmd_sink_cycle() -> int:
    # Importing gui.sink_cycle pulls PySide6 transitively (the gui
    # package's __init__ doesn't, but Settings does). To stay
    # GUI-free, inline the cycle logic here.
    import shutil
    import subprocess

    if not shutil.which("pactl"):
        print("error: pactl not found on PATH", file=sys.stderr)
        return 1

    settings = _load_settings()
    excluded = set(settings.get("default_sink_cycle_exclude") or [])
    preferred = ("SteelGame", "SteelChat", "SteelMedia", "SteelHDMI")

    # List loaded sinks.
    try:
        r = subprocess.run(
            ["pactl", "list", "sinks", "short"],
            capture_output=True, text=True, timeout=3,
        )
    except Exception as e:
        print(f"error: pactl list failed: {e}", file=sys.stderr)
        return 1
    available = [
        line.split("\t")[1]
        for line in r.stdout.splitlines()
        if "\t" in line and len(line.split("\t")) >= 2
    ]
    candidates = [
        s for s in preferred
        if s in available and s not in excluded
    ]
    if not candidates:
        print(
            "error: no eligible SteelVoiceMix sinks loaded "
            f"(available={available!r}, excluded={sorted(excluded)!r})",
            file=sys.stderr,
        )
        return 1

    # Find current default.
    try:
        r = subprocess.run(
            ["pactl", "info"],
            capture_output=True, text=True, timeout=3,
        )
    except Exception as e:
        print(f"error: pactl info failed: {e}", file=sys.stderr)
        return 1
    prev = ""
    for line in r.stdout.splitlines():
        if line.startswith("Default Sink:"):
            prev = line.split(":", 1)[1].strip()
            break

    if prev in candidates:
        idx = (candidates.index(prev) + 1) % len(candidates)
    else:
        idx = 0
    new = candidates[idx]
    if new == prev:
        print(f"already on {new}")
        return 0

    try:
        r = subprocess.run(
            ["pactl", "set-default-sink", new],
            capture_output=True, text=True, timeout=3,
        )
    except Exception as e:
        print(f"error: pactl set-default-sink failed: {e}", file=sys.stderr)
        return 1
    if r.returncode != 0:
        print(
            f"error: pactl set-default-sink {new} failed: {r.stderr.strip()}",
            file=sys.stderr,
        )
        return 1

    print(f"{prev or '?'} → {new}")
    return 0


# --------------------------------------------------------------- init / clean

# The single user-side PipeWire tweak we ship as opt-in.
# `default.clock.allowed-rates = [ 48000 ]` prevents PipeWire from
# rebuilding the entire graph when a stream comes in at 44.1kHz (some
# YouTube videos do); resampling happens per-stream which is cheap and
# avoids the global graph rebuild that's audible as a brief glitch.
# Deliberately NO `pulse.min.req` / `min.frag` / `min.quantum` settings
# — those broke browser AV-sync in earlier testing. Conservative scope.
_PW_CONFIG_PATH = "~/.config/pipewire/pipewire.conf.d/99-steelvoicemix.conf"
_PW_CONFIG_BODY = """\
# Generated by `steelvoicemix-cli init`. Safe to edit / delete.
# Locks PipeWire's graph rate to 48kHz so streams at other rates
# (44.1kHz YouTube clips etc.) don't trigger a graph rebuild that
# briefly glitches audio. Per-stream resampling kicks in instead.
context.properties = {
    default.clock.allowed-rates = [ 48000 ]
}
"""


def _confirm(prompt: str, assume_yes: bool) -> bool:
    if assume_yes:
        return True
    try:
        ans = input(f"{prompt} [y/N] ").strip().lower()
    except (EOFError, KeyboardInterrupt):
        print()
        return False
    return ans in ("y", "yes")


def _cmd_init(argv: list[str]) -> int:
    """Drop the user-side PipeWire config. Shows what will be written
    and asks for confirmation unless --yes is passed."""
    import shutil
    import subprocess

    assume_yes = "--yes" in argv or "-y" in argv
    target = os.path.expanduser(_PW_CONFIG_PATH)
    target_dir = os.path.dirname(target)

    print("steelvoicemix-cli init — what this will do:")
    print()
    print(f"  • Create {target_dir}/ if missing")
    print(f"  • Write the PipeWire config below to {target}")
    print()
    print("    ┌─" + "─" * 60)
    for line in _PW_CONFIG_BODY.splitlines():
        print(f"    │ {line}")
    print("    └─" + "─" * 60)
    print()
    print("Warning: this is a SYSTEM-LEVEL PipeWire config. It applies")
    print("to every audio app, not just SteelVoiceMix. The change is")
    print("conservative (just locks rate to 48kHz) but if you have a")
    print("very specific setup that relies on rate switching, skip this.")
    print()
    if os.path.exists(target):
        print(f"NOTE: {target} already exists. Choosing yes will overwrite.")
        print()

    if not _confirm("Proceed?", assume_yes):
        print("aborted.")
        return 0

    try:
        os.makedirs(target_dir, exist_ok=True)
        with open(target, "w") as f:
            f.write(_PW_CONFIG_BODY)
    except OSError as e:
        print(f"error: failed to write {target}: {e}", file=sys.stderr)
        return 1

    print(f"wrote {target}")
    print()
    print("Restart PipeWire so the change takes effect:")
    print("  systemctl --user restart pipewire pipewire-pulse wireplumber \\")
    print("                            steelvoicemix.service")
    print()
    print("Tip: the trailing steelvoicemix.service restart is important —")
    print("a pipewire restart tears down our virtual sinks and the daemon")
    print("rebuilds them. The watchdog catches this within ~10s but a")
    print("manual restart is faster.")
    return 0


def _cmd_clean(argv: list[str]) -> int:
    """Remove what `init` wrote. Doesn't touch any other files in
    `pipewire.conf.d/` — just our owned one."""
    assume_yes = "--yes" in argv or "-y" in argv
    target = os.path.expanduser(_PW_CONFIG_PATH)

    if not os.path.exists(target):
        print(f"{target} does not exist — nothing to clean.")
        return 0

    print(f"steelvoicemix-cli clean — will remove:")
    print(f"  {target}")
    print()
    if not _confirm("Proceed?", assume_yes):
        print("aborted.")
        return 0

    try:
        os.remove(target)
    except OSError as e:
        print(f"error: failed to remove {target}: {e}", file=sys.stderr)
        return 1

    print(f"removed {target}")
    print()
    print("Restart PipeWire to pick up the default behaviour:")
    print("  systemctl --user restart pipewire pipewire-pulse wireplumber \\")
    print("                            steelvoicemix.service")
    return 0


# --------------------------------------------------------------- diagnose

# A check function returns (status, message) where status is one of
# "ok", "warn", "fail", "info". `diagnose` aggregates all of them and
# prints a coloured summary. No exit code coupling — diagnose always
# returns 0 unless the framework itself errors; the user reads the
# output to decide if anything's wrong.

_OK = "✓"
_WARN = "⚠"
_FAIL = "✗"
_INFO = "·"


def _check_pipewire_running() -> tuple[str, str]:
    import subprocess
    try:
        r = subprocess.run(
            ["pactl", "info"], capture_output=True, text=True, timeout=3
        )
    except Exception as e:
        return "fail", f"pactl info failed: {e}"
    if r.returncode != 0:
        return "fail", "pactl info returned non-zero — PipeWire not running?"
    server = ""
    for line in r.stdout.splitlines():
        if line.startswith("Server Name:"):
            server = line.split(":", 1)[1].strip()
    return "ok", f"PipeWire reachable ({server or 'unknown server'})"


def _check_headset_usb() -> tuple[str, str]:
    import shutil
    import subprocess
    if not shutil.which("lsusb"):
        return "info", "lsusb not on PATH; skipping USB probe"
    try:
        r = subprocess.run(
            ["lsusb", "-d", "1038:12e0"],
            capture_output=True, text=True, timeout=3,
        )
    except Exception as e:
        return "fail", f"lsusb failed: {e}"
    if r.stdout.strip():
        return "ok", "Arctis Nova Pro Wireless base station detected on USB"
    # Try the wired variants too — same fault domain.
    try:
        r2 = subprocess.run(
            ["lsusb"],
            capture_output=True, text=True, timeout=3,
        )
    except Exception:
        r2 = None
    if r2 and any(
        pid in r2.stdout
        for pid in ("1038:12cb", "1038:12cd", "1038:12e5", "1038:225d")
    ):
        return "ok", "Arctis Nova Pro variant (wired/Xbox) detected"
    return "fail", "Arctis Nova Pro base station NOT visible on USB"


def _check_steel_sinks() -> tuple[str, str]:
    import subprocess
    try:
        r = subprocess.run(
            ["pactl", "list", "sinks", "short"],
            capture_output=True, text=True, timeout=3,
        )
    except Exception as e:
        return "fail", f"pactl list sinks short failed: {e}"
    sinks = [
        line.split("\t")[1]
        for line in r.stdout.splitlines()
        if "\t" in line and len(line.split("\t")) >= 2
    ]
    have = [s for s in ("SteelGame", "SteelChat", "SteelMedia", "SteelHDMI") if s in sinks]
    if not have:
        return "fail", (
            "No Steel sinks loaded — daemon not running, or it can't "
            "talk to the headset"
        )
    if "SteelGame" in have and "SteelChat" in have:
        extras = [s for s in have if s not in ("SteelGame", "SteelChat")]
        msg = "core sinks present (SteelGame, SteelChat)"
        if extras:
            msg += f" + {', '.join(extras)}"
        return "ok", msg
    return "warn", f"partial Steel sinks: {', '.join(have)}"


def _check_loopback_quantum() -> tuple[str, str]:
    """Loopback nodes should NOT be at quantum=16 (the old bug).
    Healthy values: 256+, ideally matching the filter chain (~960-1024)."""
    import shutil
    import subprocess
    if not shutil.which("pw-top"):
        return "info", "pw-top not on PATH; skipping quantum check"
    try:
        r = subprocess.run(
            ["pw-top", "-b", "-n", "1"],
            capture_output=True, text=True, timeout=4,
        )
    except Exception as e:
        return "info", f"pw-top failed: {e}"
    bad = []
    found_any = False
    for line in r.stdout.splitlines():
        if "loopback" not in line:
            continue
        parts = line.split()
        if len(parts) < 4:
            continue
        # parts: STATE ID QUANT RATE ... NAME...
        try:
            quant = int(parts[2])
        except ValueError:
            continue
        if quant <= 0:
            continue  # suspended; not informative
        found_any = True
        if quant < 128:
            bad.append((quant, parts[-1]))
    if not found_any:
        return "info", (
            "no active loopback nodes seen (start playing audio "
            "to verify quantum)"
        )
    if bad:
        details = ", ".join(f"{n}@QUANT={q}" for q, n in bad)
        return "warn", (
            f"loopback nodes at suspiciously-low quantum: {details} "
            "— upgrade to steelvoicemix 0.4.2~beta10 or later"
        )
    return "ok", "loopback quantum looks healthy"


def _check_filter_chain_processes() -> tuple[str, str]:
    import subprocess
    try:
        r = subprocess.run(
            ["pgrep", "-fa", "pipewire -c .*steelvoicemix.*filter-chains"],
            capture_output=True, text=True, timeout=3,
        )
    except Exception as e:
        return "info", f"pgrep failed: {e}"
    if not r.stdout.strip():
        return "warn", "no steelvoicemix filter-chain processes running"
    n = len([l for l in r.stdout.splitlines() if l.strip()])
    return "ok", f"{n} filter-chain process(es) alive"


def _check_recent_pipewire_glitches() -> tuple[str, str]:
    import shutil
    import subprocess
    if not shutil.which("journalctl"):
        return "info", "journalctl not available; skipping log check"
    try:
        r = subprocess.run(
            [
                "journalctl", "--user", "--since", "5 minutes ago",
                "--no-pager",
            ],
            capture_output=True, text=True, timeout=5,
        )
    except Exception as e:
        return "info", f"journalctl failed: {e}"
    bad_patterns = [
        "spa.alsa: ", "out of buffers", "No input node for loopback",
        "link failed: item deactivated",
    ]
    hits = sum(
        1 for line in r.stdout.splitlines()
        if any(p in line for p in bad_patterns)
    )
    if hits == 0:
        return "ok", "no PipeWire glitch events in last 5 min"
    return "warn", (
        f"{hits} PipeWire glitch-class event(s) in last 5 min — "
        "expect occasional audio glitches"
    )


def _check_user_pw_config() -> tuple[str, str]:
    p = os.path.expanduser(_PW_CONFIG_PATH)
    if os.path.exists(p):
        return "ok", f"steelvoicemix-cli init config installed ({p})"
    return "info", "no `init` config installed (optional, see `init -h`)"


def _check_daemon_socket() -> tuple[str, str]:
    xdg = os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{os.getuid()}"
    sock = os.path.join(xdg, "steelvoicemix.sock")
    if not os.path.exists(sock):
        return "fail", (
            f"daemon socket missing at {sock} — service not running? "
            "Try: systemctl --user status steelvoicemix.service"
        )
    return "ok", "daemon socket present"


def _cmd_diagnose(argv: list[str]) -> int:
    """Read-only system check. Prints status of each thing the daemon
    relies on, plus common pathological patterns we've seen in the wild."""
    print("steelvoicemix-cli diagnose")
    print()
    checks = [
        ("PipeWire reachable",        _check_pipewire_running),
        ("Headset on USB",            _check_headset_usb),
        ("Daemon socket",             _check_daemon_socket),
        ("Steel virtual sinks",       _check_steel_sinks),
        ("Filter chain processes",    _check_filter_chain_processes),
        ("Loopback quantum healthy",  _check_loopback_quantum),
        ("Recent PipeWire log",       _check_recent_pipewire_glitches),
        ("User PipeWire config",      _check_user_pw_config),
    ]
    glyph = {"ok": _OK, "warn": _WARN, "fail": _FAIL, "info": _INFO}
    for name, fn in checks:
        try:
            status, msg = fn()
        except Exception as e:
            status, msg = "info", f"check raised {type(e).__name__}: {e}"
        print(f"  {glyph.get(status, '?')} {name:<28}  {msg}")
    print()
    print("Legend: ✓ ok  ⚠ warn  ✗ fail  · info")
    return 0


# --------------------------------------------------------------- dispatch

_USAGE = """\
usage: steelvoicemix-cli <subcommand> [args]

Subcommands:
  sink cycle              Advance default sink between loaded Steel sinks.
                          Bind to a DE keyboard shortcut for global hotkey.
  init [--yes|-y]         Drop a small user-side PipeWire config that
                          locks the graph rate to 48kHz. Confirms first.
  clean [--yes|-y]        Remove what `init` wrote.
  diagnose                Read-only system check; print what looks
                          healthy and what doesn't.
"""


def main(argv: list[str]) -> int:
    if len(argv) >= 3 and argv[1] == "sink" and argv[2] == "cycle":
        return _cmd_sink_cycle()
    if len(argv) >= 2 and argv[1] == "init":
        return _cmd_init(argv[2:])
    if len(argv) >= 2 and argv[1] == "clean":
        return _cmd_clean(argv[2:])
    if len(argv) >= 2 and argv[1] == "diagnose":
        return _cmd_diagnose(argv[2:])
    print(_USAGE, file=sys.stderr)
    return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
